replicaCount: 1
image:
  repository: invisiblelad/dogbreed
  tagV1: v1
  tagV2: v4
  pullPolicy: IfNotPresent

env:
  MONGO_URL: "mongo-service"
  MONGO_PORT: "27017"
  MONGO_DATABASE: "dogbreed"
  MONGO_COLLECTION: "dogs"

service:
  name: dogbreed-service
  port: 8080
  type: ClusterIP