apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-v1
  labels:
    app: dogbreed
    version: v1
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: dogbreed
      version: v1
  template:
    metadata:
      labels:
        app: dogbreed
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: dogbreed
        image: {{ .Values.image.repository }}:{{ .Values.image.tagV1 }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-v2
  labels:
    app: dogbreed
    version: v2
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: dogbreed
      version: v2
  template:
    metadata:
      labels:
        app: dogbreed
        version: v2
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: dogbreed
        image: {{ .Values.image.repository }}:{{ .Values.image.tagV2 }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        {{- range $key, $value := .Values.env }}
        - name: {{ $key }}
          value: "{{ $value }}"
        {{- end }}