replicaCount: 1
image:
  repository: mongo
  tag: latest
  pullPolicy: IfNotPresent



mongodb:
  username: admin
  password: password
  authEnabled: true

serviceAccount:
  create: true
service:
  name: mongo-service
  port: 27017
  type: ClusterIP

storage:
  size: 1Gi
  accessMode: ReadWriteOnce
  storageClassName: "standard"