replicaCount: 1
image:
  repository: mongo
  tag: latest
  pullPolicy: IfNotPresent

env:
  MONGO_INITDB_ROOT_USERNAME: "admin"
  MONGO_INITDB_ROOT_PASSWORD: "password"

service:
  name: mongo-service
  port: 27017
  type: ClusterIP

storage:
  size: 1Gi
  accessMode: ReadWriteOnce
  storageClassName: "standard"